### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by denis-roy** [BlackStartx/PyCharm-Blender-Plugin#13]
Good day @BlackStartx 

First of all, I just found your plugin and want to say a big heartfelt thank you for it! 💯

Blender can use a number of environment variables and in my current setup, I must use the following two:
BLENDER_USER_CONFIG
BLENDER_USER_SCRIPTS

I'm wondering if there is a way within your plugin for me to set these up before the instances are started?

For normal Blender launching, I have a batch file that SETs them before executing Blender and while, for a regular Python program, I would normally do it through PyCharm's run configurations, I tried starting Blender with the `--python C:\Users\User\AppData\Local\Temp\BlendCharm\pycharm_connector.py --`  argument as an external tool in the run config but it didn't work ¯\\_(ツ)_/¯

Another potential way... Could it be even possible to use the standard run configuration settings to set the ENV variable and then to trigger your plugin?

Thanks again :)

**Comment by BlackStartx** [comment]
Hi Denis~
First of all sorry so much for the delay of the reply, and thanks so much for the words~ ♥ 

By the way yeah, starting Blender with PyCharm's run configurations only start the client socket (pycharm_connector.py) but doesn't start the server one, thus it's not working~

I will have to implement a way to allow the user to define environment variables, right now you have 0 power of customization over the configuration. (This project started as a personal project for fun, it was not expecting configurable stuff :c)

Meanwhile a possible workarround I'm tinking may be to manually add them to the Windows system variables~

![image](https://user-images.githubusercontent.com/26898122/230786477-e43c6929-564a-4cf0-a2c6-f548a81b92a3.png)

This is a **LOT** dirty, but it will do the trick as long as they are not required to change too much.

On the other end you may change and set them directly in the script on the `%LocalAppData%\Temp\BlendCharm` path, but keep in mind that the file will be regenerated on PyCharm restart.

I definitely have to do something to make this easier.

Sorry so much for the troubles,
I hope the workarround may do the trick meanwhile an easier method will be developed~ ♥

**Comment by BlackStartx** [comment]
Hi again Denis~

I want to publish a new release soon adding the option to handle environment variables.

But first... Sorry even more for the delay this time :c
I'm not good with Swing UI, and this caused some delays.

By the way, the idea is to add them in the Blender configuration window, so you may have different runnable configurations (eventually using the same Blender executable) with different environment variables.

I do think this would do the trick perfectly, do you have any suggestion?

Thanks once again~ 🌸

**Comment by BlackStartx** [comment]
I've managed to implement a table containing the list (key, value) of the defined enviroment variables.

The only things that still triggers me is that random **white aurea** around the table:

![image](https://user-images.githubusercontent.com/26898122/235279065-f9cfe4ca-895a-43d8-9375-556562c82542.png)

###### I've tried a lot of stuff (setBorder(null), etc...) but I can't get rid of it .-.

Anyway, at runtime the enviroment variable can be read by:

![image](https://user-images.githubusercontent.com/26898122/235279043-d982739e-49c6-4900-8811-5e4fbcbea7f2.png)

Once I've defeated the **white aurea** I'll publish a release!

Sorry that this took 3 weeks~ ^-^'

**Comment by denis-roy** [comment]
Good day @BlackStartx 

I did not see those last few weeks fly by me, but I can see you were hard at work! This will be incredibly useful, once again thank you! 

💯 / 💯

**Comment by BlackStartx** [comment]
Hi, small update for why it's taking longer than a day...

I want to implement a collapsable group in my dialog like the one here:

![image](https://user-images.githubusercontent.com/26898122/235386583-ada06f0d-40d4-4c1c-9d08-9a5758e71450.png)

It will have the "**Optional Settings**" label and it will contains all the extra... well, optional settings.

This way new user will not see too many stuff if they just want to setup the Blender Executable~
The problem is that I'm unable to find the JComponent for it and I'm starting to hate Swing even more! :D

Anyway, In the meanwhile I'll publish here the two beta version that support the enviroment variables but have the ugly UI, so if you don't mind and wish to experiment with it you can do it~ :3 ✨ 

[Blend-Charm.2023.1-Beta.Community.Edition.zip](https://github.com/BlackStartx/PyCharm-Blender-Plugin/files/11362932/Blend-Charm.2023.1-Beta.Community.Edition.zip)
[Blend-Charm.2023.1-Beta.Professional.Edition.zip](https://github.com/BlackStartx/PyCharm-Blender-Plugin/files/11362928/Blend-Charm.2023.1-Beta.Professional.Edition.zip)

They should be stable, and the data of the enviroments will be kept on the final release as well (unless I **REALLY** need to change stuff, but probably not)

**Comment by denis-roy** [comment]
Thank you, that is very cool! I will try to experiment a bit with it during the coming weekend!

**Comment by denis-roy** [comment]
Did a little testing and it does works wonderfully so far! 🤩 

Thank you!
